In [1]:
import pandas as pd
import numpy as np

In [2]:
telco=pd.read_csv("Telco.csv",na_values=" ")

In [3]:
telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [4]:
telco.drop( "customerID", axis=1,inplace=True)

In [5]:
# I will assign "numeric values" for our variables that are categorical.
dummies=pd.get_dummies(telco,drop_first=True)
dummies_without_na=dummies.dropna()

In [6]:
dummies_without_na.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
0              0       1           29.85         29.85            0   
1              0      34           56.95       1889.50            1   
2              0       2           53.85        108.15            1   
3              0      45           42.30       1840.75            1   
4              0       2           70.70        151.65            0   

   Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0            1               0                 0   
1            0               0                 1   
2            0               0                 1   
3            0               0                 0   
4            0               0                 1   

   MultipleLines_No phone service  MultipleLines_Yes  ...  StreamingTV_Yes  \
0                               1                  0  ...                0   
1                               0                  0  ...                0   
2                               0                  0  ...                0   
3                               1                  0  ...                0   
4                               0                  0  ...                0   

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                    0                    0   
1                                    0                    0   
2                                    0                    0   
3                                    0                    0   
4                                    0                    0   

   Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0                  0                  0                     1   
1                  1                  0                     0   
2                  0                  0                     1   
3                  1                  0                     0   
4                  0                  0                     1   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  Churn_Yes  
0                           0          0  
1                           1          0  
2                           1          1  
3                           0          0  
4                           0          1  

[5 rows x 31 columns]

In [7]:
X=dummies_without_na.drop(["Churn_Yes"],axis=1)
y=dummies_without_na.Churn_Yes

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
# So, that there is no data snooping in our model
# I split the dataset train(0.8) and test (0,2).
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=2, stratify=y)

**Logistic Regression**

In [11]:
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [12]:
ypred=model.predict(X_test)
ypred

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [13]:
y.shape

(7032,)

In [14]:
X.shape

(7032, 30)

In [15]:
X

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
0                 0       1           29.85         29.85            0   
1                 0      34           56.95       1889.50            1   
2                 0       2           53.85        108.15            1   
3                 0      45           42.30       1840.75            1   
4                 0       2           70.70        151.65            0   
...             ...     ...             ...           ...          ...   
7038              0      24           84.80       1990.50            1   
7039              0      72          103.20       7362.90            0   
7040              0      11           29.60        346.45            0   
7041              1       4           74.40        306.60            1   
7042              0      66          105.65       6844.50            1   

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0               1               0                 0   
1               0               0                 1   
2               0               0                 1   
3               0               0                 0   
4               0               0                 1   
...           ...             ...               ...   
7038            1               1                 1   
7039            1               1                 1   
7040            1               1                 0   
7041            1               0                 1   
7042            0               0                 1   

      MultipleLines_No phone service  MultipleLines_Yes  ...  \
0                                  1                  0  ...   
1                                  0                  0  ...   
2                                  0                  0  ...   
3                                  1                  0  ...   
4                                  0                  0  ...   
...                              ...                ...  ...   
7038                               0                  1  ...   
7039                               0                  1  ...   
7040                               1                  0  ...   
7041                               0                  1  ...   
7042                               0                  0  ...   

      StreamingTV_No internet service  StreamingTV_Yes  \
0                                   0                0   
1                                   0                0   
2                                   0                0   
3                                   0                0   
4                                   0                0   
...                               ...              ...   
7038                                0                1   
7039                                0                1   
7040                                0                0   
7041                                0                0   
7042                                0                1   

      StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                       0                    0   
1                                       0                    0   
2                                       0                    0   
3                                       0                    0   
4                                       0                    0   
...                                   ...                  ...   
7038                                    0                    1   
7039                                    0                    1   
7040                                    0                    0   
7041                                    0                    0   
7042                                    0                    1   

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0                     0                  0                     1   
1                     1                  0                   

In [16]:
score=model.score(X_test, y_test)
print("Score of the model is: ",score)

Score of the model is:  0.798862828713575


In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score,precision_score, classification_report, f1_score

In [18]:
ypred=model.predict(X_test)
ypred

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [19]:
print("Accuracy Score: ",accuracy_score(y_test,ypred))
print("Confusion Matrix: \n",confusion_matrix(y_test,ypred))
print("Recall Score: ",recall_score(y_test,ypred))
print("Precision Score: ",precision_score(y_test,ypred))
print("F1 Score: ",f1_score(y_test,ypred))
print("-----------------------------------------------------------------------------")
print(classification_report(y_test,ypred))

Accuracy Score:  0.798862828713575
Confusion Matrix: 
 [[921 112]
 [171 203]]
Recall Score:  0.5427807486631016
Precision Score:  0.6444444444444445
F1 Score:  0.5892597968069665
-----------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1033
           1       0.64      0.54      0.59       374

    accuracy                           0.80      1407
   macro avg       0.74      0.72      0.73      1407
weighted avg       0.79      0.80      0.79      1407



**Naive Bayes**

In [20]:
from sklearn.naive_bayes import GaussianNB

In [21]:
nb=GaussianNB()
nb.fit(X_train,y_train)
nb.score(X_test,y_test)

0.650319829424307

In [22]:
predictions=nb.predict(X_test)

In [23]:
comp=zip(predictions,y_test)
list(comp)

[(0, 0),
 (1, 0),
 (1, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 0),
 (1, 0),
 (0, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 0),
 (1, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 

**K-NN**

In [24]:
from sklearn.neighbors import KNeighborsClassifier

-->I will investigate Whick k value best for the model (for: 1<k<#of_features)



In [25]:
liste=[]
for k in range(1,X.shape[1]):
  model=KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train,y_train)
  liste.append([model.score(X_test,y_test),k])
df=pd.DataFrame(liste, columns=["Score","Neighbours_number"])
print(df)

       Score  Neighbours_number
0   0.722814                  1
1   0.758351                  2
2   0.756930                  3
3   0.764037                  4
4   0.766880                  5
5   0.778252                  6
6   0.771855                  7
7   0.781805                  8
8   0.775409                  9
9   0.781805                 10
10  0.776119                 11
11  0.779673                 12
12  0.771855                 13
13  0.773276                 14
14  0.778252                 15
15  0.779673                 16
16  0.779673                 17
17  0.788202                 18
18  0.781095                 19
19  0.784648                 20
20  0.776830                 21
21  0.781095                 22
22  0.781095                 23
23  0.781805                 24
24  0.782516                 25
25  0.781095                 26
26  0.782516                 27
27  0.777541                 28
28  0.777541                 29


In [26]:
df.Score.max()

0.7882018479033405

--> Appearently, if neighbour number is 18, score of our model is more higher!!



---> Now I will change the metrics while n_neighbours remaining same (18).


In [27]:
  model=KNeighborsClassifier(n_neighbors=18, metric="euclidean")
  model.fit(X_train,y_train)


KNeighborsClassifier(metric='euclidean', n_neighbors=18)

In [28]:
a=[]
metric_liste=["manhattan","euclidean","cosine"]
for i in metric_liste:
  model=KNeighborsClassifier(n_neighbors=6, metric=i)
  model.fit(X_train,y_train)
  model.score(X_test,y_test)
  a.append([i,model.score(X_test,y_test)])
dff=pd.DataFrame(a, columns=["Metric","Score"])
dff

Metric     Score
0  manhattan  0.773987
1  euclidean  0.778252
2     cosine  0.782516

In [29]:
dff.Score.max()

0.7825159914712153

--> Appearently, **cosine** distance best for our KNN classification model.